packer {
  required_plugins {
    xenserver = {
      version = ">= v0.7.0"
      source  = "github.com/ddelnano/xenserver"
    }
  }
}

variable "remote_host" {
  type        = string
  description = "The IP or FQDN of your XCP-ng. It must be the master"
  sensitive   = true
  default     = "node_ip"
}

variable "remote_username" {
  type        = string
  description = "The username used to interact with your XCP-ng"
  sensitive   = true
  default     = "root"
}

variable "remote_password" {
  type        = string
  description = "The password used to interact with your XCP-ng"
  sensitive   = true
  default     = "node_password"
}

variable "sr_iso_name" {
  type        = string
  description = "The ISO-SR Packer will use"
  default     = "PROD172_NFS171COREC14_ST19_ISOS"
}

variable "sr_name" {
  type        = string
  description = "The name of the SR Packer will use"
  default     = "PROD171_NFS171COREC14_ST19"
}

source "xenserver-iso" "windows2022" {
  iso_checksum                 = "8ce0eee81f40b0329ec1ffb80a5d0ac0f3fa3f6b5af7378ad17a5a22002d8c972d454902edf44b5170fd2eec0bb22cb1f7540c96c6af615a08c132d706d99a94"
  iso_url                      = "http://nexus.example.com/repository/ISOS/WindowsServer2022FR.iso"
  sr_iso_name                  = var.sr_iso_name
  sr_name                      = var.sr_name
  remote_host                  = var.remote_host
  remote_password              = var.remote_password
  remote_username              = var.remote_username
  ssh_disable_agent_forwarding = true
  ssh_pty                      = true

  boot_command = [
    "<wait><wait><wait><enter>"
  ]

  vm_name         = "Win2022FR_template"
  vm_description  = "VM for Windows Server 2022 FR"
  vcpus_max       = 4
  vcpus_atstartup = 4
  vm_memory       = 16384 # MB
  network_names   = ["MAD4-CORE-ADM-MGMT-VLAN60"]
  disk_size       = 81920 # MB
  disk_name       = "Win2022FR_template_disk"
  floppy_files = [
    "./floppy/fr22/autounattend.xml",
    "./floppy/fr22/cloudbase-init-unattend.conf",
    "./floppy/fr22/cloudbase-init.conf",
    "./floppy/fr22/Unattend.xml",
    "./floppy/fr22/2k22unattend.xml",
    "./scripts/Cleanup.ps1",
    "./scripts/ConfigureRemotingForAnsible.ps1",
    "./scripts/CopyFiles.ps1",
    "./scripts/WinUpdate.ps1",
    "./scripts/InstallInitialSetup.ps1",
    "./scripts/Sysprep.ps1"
  ]
  vm_tags                = ["Generated by Packer"]
  communicator           = "winrm"
  winrm_username         = "Administrateur"
  winrm_password         = "Password2022!"
  winrm_timeout          = "6h"
  winrm_insecure         = true
  winrm_use_ssl          = true
  ssh_username           = "Administrateur"
  ssh_password           = "Password2022!"
  ssh_wait_timeout       = "60000s"
  ssh_handshake_attempts = 10000
  output_directory       = "packer-Win2022FR"
  keep_vm                = "never"
  format                 = "vdi_vhd"
}

build {
  name    = "Win2022FR-XenServer"
  sources = ["xenserver-iso.windows2022"]

  provisioner "powershell" {
    scripts          = ["scripts/WinUpdate.ps1"]
    valid_exit_codes = [0, 2300218]
  }

  provisioner "windows-restart" {
    pause_before    = "30s"
    restart_timeout = "30m"
  }

  provisioner "powershell" {
    scripts = ["scripts/WinUpdate.ps1"]
  }

  provisioner "windows-restart" {
    restart_timeout = "30m"
  }

  provisioner "powershell" {
    scripts = ["scripts/Cleanup.ps1"]
  }

  provisioner "windows-restart" {
    restart_timeout = "30m"
  }

  provisioner "powershell" {
    scripts = ["scripts/Sysprep.ps1"]
  }

  provisioner "windows-restart" {
    restart_timeout = "30m"
  }

}
